clc;
clear all;
close all;
n=-6:1:6;
x1=[-1,-1,-1,-1,-1,-1,1,1,1,1,1,1,1];
x2=fliplr(x1);
subplot(2,2,1);
stem(n,x1);
grid on;
xlabel('n');
ylabel('x1');
title('Given Signal');
subplot(2,2,2);
stem(n,x2);
grid on;
xlabel('n');
ylabel('x2');
title('Flipped Signal');
even=(x1+x2)/2;
odd=(x1-x2)/2;
subplot(2,2,3);
stem(n,even);
grid on;
xlabel('n');
ylabel('even');
title('even part of the signal');
subplot(2,2,4);
stem(n,odd);
grid on;
xlabel('n');
ylabel('odd');
title('odd part of the signal');
